//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMultipleContracts.ConsumedService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumedService.IGetData")]
    public interface IGetData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetData/GetSomeData", ReplyAction="http://tempuri.org/IGetData/GetSomeDataResponse")]
        string GetSomeData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetData/GetSomeData", ReplyAction="http://tempuri.org/IGetData/GetSomeDataResponse")]
        System.Threading.Tasks.Task<string> GetSomeDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataChannel : TestMultipleContracts.ConsumedService.IGetData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataClient : System.ServiceModel.ClientBase<TestMultipleContracts.ConsumedService.IGetData>, TestMultipleContracts.ConsumedService.IGetData {
        
        public GetDataClient() {
        }
        
        public GetDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSomeData(int value) {
            return base.Channel.GetSomeData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetSomeDataAsync(int value) {
            return base.Channel.GetSomeDataAsync(value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsumedService.IDoMoreWork")]
    public interface IDoMoreWork {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoMoreWork/DoMoreWork", ReplyAction="http://tempuri.org/IDoMoreWork/DoMoreWorkResponse")]
        string DoMoreWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoMoreWork/DoMoreWork", ReplyAction="http://tempuri.org/IDoMoreWork/DoMoreWorkResponse")]
        System.Threading.Tasks.Task<string> DoMoreWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoMoreWorkChannel : TestMultipleContracts.ConsumedService.IDoMoreWork, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoMoreWorkClient : System.ServiceModel.ClientBase<TestMultipleContracts.ConsumedService.IDoMoreWork>, TestMultipleContracts.ConsumedService.IDoMoreWork {
        
        public DoMoreWorkClient() {
        }
        
        public DoMoreWorkClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoMoreWorkClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoMoreWorkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoMoreWorkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoMoreWork() {
            return base.Channel.DoMoreWork();
        }
        
        public System.Threading.Tasks.Task<string> DoMoreWorkAsync() {
            return base.Channel.DoMoreWorkAsync();
        }
    }
}
